name: Test

on:
  pull_request:
jobs:
  terraform:
    name: Run test
    runs-on: ubuntu-latest

    steps:
      - name: Run Always
        run: echo always

      - name: Run on label
        # if: ${{ github.event.label.name == 'automerge' }}
        if: contains( github.event.pull_request.labels.*.name, 'test')
        run: echo not-always bro

      - name: Check labels in fly
        run: |
          labels=$(curl -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/gagarinfan/auto-pr-test/pulls/${{github.event.number}} | jq '.labels')
          echo $labels
