name: Test

on:
  pull_request:
    types: [ opened, "!labeled"]
jobs:
  terraform:
    name: Run test
    runs-on: ubuntu-latest

    steps:
      - name: Run Always
        run: echo always

      - name: Run on label
        # if: ${{ github.event.label.name == 'automerge' }}
        if: contains( github.event.pull_request.labels.*.name, 'automerge')
        run: echo not-always bro
