name: Test

on:
  pull_request:
jobs:
  terraform:
    name: Run test
    runs-on: ubuntu-latest

    steps:
      - name: Run Always
        run: echo always

      - name: Run on label
        # if: ${{ github.event.label.name == 'automerge' }}
        if: contains( github.event.pull_request.labels.*.name, 'test')
        run: echo not-always bro

      - name: Check labels in fly
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
            github-token: '${{ secrets.GITHUB_TOKEN }}'
            valid-labels: 'test'
            pull-request-number: '${{ github.event.pull_request.number }}'