name: Merge automat

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
jobs:
  auto-merge:
    name: Check PRs to automerge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: squash
          MERGE_RETRY_SLEEP: 30000
